# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Svj-4Y00kA8R62f9orAp7eukAHwvS_kE
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from google.colab import drive
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical

if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- 2. VERİ YÜKLEME
file_path = '/content/drive/MyDrive/customer_shopping_data.csv'

# Dosya yolu kontrolü
if not os.path.exists(file_path):
    # Eğer Drive'da bulamazsa local'e bakar
    file_path = 'customer_shopping_data.csv'
    if not os.path.exists(file_path):
         raise FileNotFoundError(f"❌ Dosya bulunamadı! Lütfen dosyanın '/content/drive/MyDrive/' altında olduğundan emin ol.")

print(f"📂 Dosya okunuyor: {file_path}")


try:
    df = pd.read_csv(file_path, on_bad_lines='skip')
    print(f"✅ Veri başarıyla yüklendi! Toplam satır: {len(df)}")
except Exception as e:
    print(f"❌ Veri okunurken kritik hata: {e}")
    # Hata durumunda işlemi durdur
    raise

# --- 3. VERİ ÖN İŞLEME ---

# A) Tarih Düzenleme
df['invoice_date'] = pd.to_datetime(df['invoice_date'], dayfirst=True, errors='coerce')
df.dropna(subset=['invoice_date'], inplace=True)

# Hafta sonu özelliği
df['is_weekend'] = df['invoice_date'].dt.weekday.apply(lambda x: 1 if x >= 5 else 0)
print("✅ 'is_weekend' özelliği eklendi.")

# B) Kategorik Değişkenleri Sayısallaştırma (Encoding)
categorical_cols = ['gender', 'category', 'payment_method', 'shopping_mall']
encoders = {}

print("\n--- Encoding İşlemi ---")
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    encoders[col] = le

    # Kontrol çıktısı
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    first_3 = list(mapping.items())[:3]
    print(f"   -> {col} kodlandı. Örn: {first_3}...")

# C) Normalizasyon
# Uyarıları (SettingWithCopy) engellemek için direkt atama yapıyoruz
scaler_age = MinMaxScaler()
df['age'] = scaler_age.fit_transform(df[['age']])

scaler_price = StandardScaler()
df['price'] = scaler_price.fit_transform(df[['price']])
print("✅ Veriler normalize edildi (Yaş: 0-1, Fiyat: Z-Score).")

print("\n--- AŞAMA 1 TAMAMLANDI ---")
print(df[['age', 'price', 'is_weekend', 'category', 'shopping_mall']].head())

# Grafik ayarları
plt.rcParams['figure.figsize'] = (14, 10)
sns.set_style("whitegrid")

# 1. KATEGORİ DAĞILIMI
plt.subplot(2, 2, 1)
# Sayısal veriyi çizdiriyoruz
ax1 = sns.countplot(x='category', data=df, order=df['category'].value_counts().index, palette='viridis')
# Eksenleri okunabilir metne çeviriyoruz
ax1.set_xticklabels(encoders['category'].inverse_transform(ax1.get_xticks()), rotation=45)
plt.title("En Çok Satılan Ürün Kategorileri")

# 2. AVM DAĞILIMI
plt.subplot(2, 2, 2)
ax2 = sns.countplot(y='shopping_mall', data=df, order=df['shopping_mall'].value_counts().index, palette='rocket')
ax2.set_yticklabels(encoders['shopping_mall'].inverse_transform(ax2.get_yticks()))
plt.title("AVM Müşteri Yoğunluğu")

# 3. HAFTANIN GÜNLERİ ANALİZİ
# Gün isimleri (0: Pazartesi - 6: Pazar)
df['day_name'] = df['invoice_date'].dt.day_name()
days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

plt.subplot(2, 2, 3)
sns.countplot(x='day_name', data=df, order=days_order, palette='coolwarm')
plt.xticks(rotation=45)
plt.title("Günlere Göre Alışveriş Sıklığı")

# 4. NORMALİZE EDİLMİŞ HARCAMA DAĞILIMI (Price)
plt.subplot(2, 2, 4)
sns.histplot(df['price'], bins=30, kde=True, color='purple')
plt.title("Harcama Dağılımı (Normalize Edilmiş)")
plt.xlabel("Z-Skoru (0 = Ortalama Fiyat)")

plt.tight_layout()
plt.show()

# İstatistiksel Özet
print(f"Toplam İşlem Sayısı: {len(df)}")
print("\nKategori Bazlı İşlem Sayıları (İlk 5):")
print(df['category'].value_counts().rename(index=dict(zip(range(len(encoders['category'].classes_)), encoders['category'].classes_))).head())

# 1. KÜMELEME (CLUSTERING)
# Model için gerekli özellikleri seçelim (zaten normalize etmiştik)
X_cluster = df[['age', 'price', 'is_weekend']]

# KMeans Modelini Kuruyoruz (K=4 Küme ideal bir başlangıçtır)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['cluster_label'] = kmeans.fit_predict(X_cluster)

# 2. SONUÇLARI YORUMLAMA (INTERPRETATION)
# Kümelerin merkez noktalarını (ortalama değerlerini) alalım
cluster_summary = df.groupby('cluster_label')[['age', 'price', 'is_weekend']].mean()

# Normalize edilmiş değerleri gerçek değerlere (TL ve Yaş) çevirelim ki anlayabilelim
# Inverse Transform işlemleri:
cluster_summary['Gerçek_Yaş'] = scaler_age.inverse_transform(cluster_summary[['age']])
cluster_summary['Gerçek_Fiyat'] = scaler_price.inverse_transform(cluster_summary[['price']])

# Tabloyu düzenleyip yazdıralım
print("\n--- Müşteri Segmentleri (K-Means Sonuçları) ---")
print(cluster_summary[['Gerçek_Yaş', 'Gerçek_Fiyat', 'is_weekend']].round(1))

# 3. KÜME DAĞILIMI
print("\nHer kümede kaç kişi var?")
print(df['cluster_label'].value_counts())

# 1. ÖZELLİK VE HEDEF BELİRLEME
# Modeli besleyeceğimiz bilgiler (Features)
X = df[['age', 'gender', 'category', 'shopping_mall', 'is_weekend']]

# Tahmin etmeye çalıştığımız değer (Target) - Normalize edilmiş fiyatı kullanıyoruz
y = df['price']

# 2. VERİ SETİNİ BÖLME (Train %80 - Test %20)
# random_state=42 sayesinde her çalıştırmada aynı ayrımı yapar (tekrarlanabilirlik)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Eğitim Seti: {X_train.shape}, Test Seti: {X_test.shape}")

# 3. BASELINE MODEL KURULUMU (Lineer Regresyon)
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)

# 4. TAHMİN VE DEĞERLENDİRME
y_pred = model_lr.predict(X_test)

# Metrikleri Hesapla (Scaled Data üzerinden)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"\n--- Baseline Model Performansı (Scaled) ---")
print(f"MAE (Ortalama Mutlak Hata): {mae:.4f}")
print(f"RMSE (Kök Ortalama Kare Hata): {rmse:.4f}")

# 5. GERÇEK TL KARŞILIĞINI GÖRMEK İÇİN
# Normalize edilmiş hatayı (örn: 0.74) gerçek TL'ye çevirelim ki iş birimi anlasın.
# scaler_price nesnesini AŞAMA 1'de oluşturmuştuk.
# Inverse transform 2D array bekler, reshape yapıyoruz.
sample_error_scaled = np.array([[mae]])
real_error_try = scaler_price.inverse_transform(sample_error_scaled)[0][0]

# Not: Inverse transform işlemi verinin ortalamasını (mean) geri ekler,
# sadece ölçek katsayısını (std) almak için standart sapma ile çarpmak daha doğrudur.
# Doğru yöntem: Hata * Standart Sapma
real_mae_try = mae * scaler_price.scale_[0]

print(f"\n--- Gerçek Dünya Hatası ---")
print(f"Model ortalama +/- {real_mae_try:.2f} TL yanılıyor.")

# --- 1. MODEL MİMARİSİ (MLP Regressor) ---
# Sequential: Katmanları arka arkaya dizmek demektir.
model_price = Sequential([
    # Girdi Katmanı + 1. Gizli Katman
    # input_shape: Modele kaç tane özellik verdiğimiz (X_train.shape[1])
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(), # Veriyi dengeler, eğitimi hızlandırır
    Dropout(0.3),         # Rastgele %30 nöronu kapat (Overfitting önleyici)

    # 2. Gizli Katman
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    # 3. Gizli Katman
    Dense(32, activation='relu'),

    # Çıktı Katmanı
    # Tek bir sayı (Fiyat) tahmin ettiğimiz için 1 nöron.
    # Aktivasyon 'linear' (veya boş) çünkü eksi veya artı herhangi bir sayı çıkabilir.
    Dense(1, activation='linear')
])

# --- 2. MODELİ DERLEME (COMPILE) ---
# Optimizer: Adam (En yaygın ve başarılı algoritma)
# Loss: MSE (Hatanın karesine odaklanır, büyük hataları daha çok cezalandırır)
# Metrics: MAE (Bizim anlayacağımız dildeki ortalama hata)
model_price.compile(optimizer='adam', loss='mse', metrics=['mae'])

# --- 3. EĞİTİM (TRAINING) ---
print("🚀 Model Eğitimi Başlıyor...")

# EarlyStopping: Eğer model 10 tur boyunca gelişmezse eğitimi erken bitir.
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history_price = model_price.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,          # Maksimum 50 tur dönsün
    batch_size=32,      # Her seferinde 32 müşteriye bakıp öğrensin
    callbacks=[early_stop],
    verbose=1           # Eğitim detaylarını göster
)

# --- 4. SONUÇ VE KAYIT ---
# Test seti üzerinde son durumu görelim
loss, mae_dl = model_price.evaluate(X_test, y_test, verbose=0)
print(f"\n✅ Derin Öğrenme Modeli Tamamlandı!")
print(f"📉 Test Seti Hata Payı (Scaled MAE): {mae_dl:.4f}")

# Gerçek TL hatasını hesaplayalım (Yaklaşık)
real_mae_dl = mae_dl * scaler_price.scale_[0]
print(f"💰 Gerçek Tahmin Hatası: +/- {real_mae_dl:.2f} TL")

# Modeli Kaydet
model_price.save('retail_price_model.h5')
print("💾 Model 'retail_price_model.h5' olarak kaydedildi.")

# --- 1. VERİ HAZIRLIĞI (Classification İçin) ---
# Girdiler: Yaş, Cinsiyet, AVM, Hafta Sonu
# NOT: Fiyatı (Price) girdilere koymuyoruz, çünkü müşteri daha ödeme yapmadı, ne alacağını tahmin etmeye çalışıyoruz.
X_cat = df[['age', 'gender', 'shopping_mall', 'is_weekend']]

# Hedef: Kategori (0: Clothing, 1: Cosmetics vb.)
y_cat_raw = df['category']

# Hedefi One-Hot Encoding'e çevirmeliyiz (Derin Öğrenme sınıflandırma formatı)
# Örn: Kategori 2 -> [0, 0, 1, 0, 0...]
num_classes = len(encoders['category'].classes_)
y_cat = to_categorical(y_cat_raw, num_classes=num_classes)

# Eğitim ve Test Setine Bölme
X_train_cat, X_test_cat, y_train_cat, y_test_cat = train_test_split(X_cat, y_cat, test_size=0.2, random_state=42)

print(f"Sınıflandırma Verisi Hazır. Sınıf Sayısı: {num_classes}")

# --- 2. MODEL MİMARİSİ (Classification MLP) ---
model_class = Sequential([
    # 1. Katman
    Dense(128, activation='relu', input_shape=(X_train_cat.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    # 2. Katman
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    # 3. Katman
    Dense(32, activation='relu'),

    # ÇIKTI KATMANI
    # Nöron sayısı = Kategori sayısı kadar (num_classes)
    # Aktivasyon = 'softmax' (Olasılık dağılımı verir)
    Dense(num_classes, activation='softmax')
])

# --- 3. DERLEME (Accuracy Burada!) ---
model_class.compile(
    optimizer='adam',
    loss='categorical_crossentropy',  # Çoklu sınıflandırma için standart kayıp fonksiyonu
    metrics=['accuracy']              # İŞTE İSTEDİĞİN METRİK
)

# --- 4. EĞİTİM ---
print("🚀 Kategori Tahmin Modeli Eğitiliyor...")
history_class = model_class.fit(
    X_train_cat, y_train_cat,
    validation_data=(X_test_cat, y_test_cat),
    epochs=50,
    batch_size=16,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)],
    verbose=1
)

# --- 5. SONUÇ ---
loss, acc = model_class.evaluate(X_test_cat, y_test_cat, verbose=0)
print(f"\n✅ Model Tamamlandı!")
print(f"🎯 Test Seti Doğruluk Oranı (Accuracy): %{acc * 100:.2f}")

# Modeli Kaydet
model_class.save('retail_category_model.h5')
print("💾 Model 'retail_category_model.h5' olarak kaydedildi.")

# --- 1. KÜTÜPHANE KURULUMU ---
# Bu satır Google'ın yapay zeka kütüphanesini Colab ortamına kurar.
!pip install -q -U google-generativeai

import google.generativeai as genai
import json

# --- 2. API AYARLARI ---
# Senin verdiğin anahtarı buraya ekledim.
API_KEY = ".env"

genai.configure(api_key=API_KEY)

# --- 3. SYSTEM PROMPT (Zeka Katmanı) ---
# Gemini'ye bir "Veri Mühendisi" gibi davranmasını emrediyoruz.
system_instruction = """
Sen bir "Veri Çıkarım Uzmanısın". Görevin, kullanıcıdan gelen doğal dil metnini analiz edip,
aşağıdaki JSON formatına dönüştürmektir.

ÇIKTI FORMATI (Sadece bu JSON'u döndür, başka açıklama yapma):
{
  "age": (integer veya null - örn: 25),
  "gender": ("Male", "Female" veya null - bağlamdan çıkar, "kız arkadaşım" denirse null al),
  "mall": (Alışveriş merkezi ismi veya null - örn: "Kanyon", "Zorlu"),
  "day_type": ("Weekend" veya "Weekday" - örn: "Cumartesi" ise Weekend, "Bugün Salı" ise Weekday),
  "payment_method": ("Credit Card", "Cash", "Debit Card" veya null),
  "intent": ("prediction" veya "chat")
}

KURALLAR:
1. Eğer bilgi yoksa "null" değerini kullan.
2. AVM isimlerini en yakın bilinen isme eşle (örn: "Kanyon AVM" -> "Kanyon").
3. Sadece JSON döndür. Markdown (```json) kullanma.
"""

# Modeli Hazırla (Hızlı ve hafif model: Flash)
model_gemini = genai.GenerativeModel(
    model_name="gemini-1.5-flash",
    system_instruction=system_instruction
)

# --- 4. TEST FONKSİYONU ---
def extract_entities(user_text):
    """
    Kullanıcı metnini alır, Gemini'ye gönderir ve JSON olarak geri döndürür.
    """
    try:
        response = model_gemini.generate_content(user_text)
        # Bazen Gemini ```json etiketi ekler, onları temizleyelim
        cleaned_text = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(cleaned_text)
    except Exception as e:
        print(f"Hata oluştu: {e}")
        return None

# --- 5. CANLI TEST ---
print("Gemini Test Ediliyor...")
ornek_cumle = "30 yaşındayım, bugün Pazar ve Zorlu Center'da kendime bir şeyler bakıyorum."
sonuc = extract_entities(ornek_cumle)

print(f"\n🗣️ Kullanıcı: {ornek_cumle}")
print(f"🤖 Gemini Çıktısı (JSON): {sonuc}")

import numpy as np

# --- MAPPING FONKSİYONU ---
def prepare_input_for_category_model(json_data):
    """
    Gemini'den gelen JSON'u, Kategori Tahmin Modeli için sayısal vektöre çevirir.
    Girdi Sırası: [age, gender, shopping_mall, is_weekend]
    """

    # 1. VARSAYILAN DEĞERLER (Eğer kullanıcı söylemediyse)
    # Veri setindeki en yaygın değerleri (Mode) varsayılan olarak seçiyoruz.
    defaults = {
        "age": 30,              # Ortalama yaş
        "gender": "Female",     # En çok bulunan cinsiyet
        "mall": "Kanyon",       # Popüler AVM
        "day_type": "Weekend"   # Haftasonu varsayımı
    }

    # JSON'dan veriyi al, yoksa varsayılanı kullan
    age_val = json_data.get("age") if json_data.get("age") is not None else defaults["age"]
    gender_val = json_data.get("gender") if json_data.get("gender") is not None else defaults["gender"]
    mall_val = json_data.get("mall") if json_data.get("mall") is not None else defaults["mall"]
    day_val = json_data.get("day_type") if json_data.get("day_type") is not None else defaults["day_type"]

    # --- 2. DÖNÜŞÜMLER (ENCODING & SCALING) ---
    input_vector = []

    # A) YAŞ (Normalize Etmeliyiz: 0-1 arası)
    # scaler_age nesnesini Aşama 1'de eğitmiştik.
    # Scaler 2D array bekler, o yüzden [[age_val]] yapıyoruz.
    age_scaled = scaler_age.transform([[age_val]])[0][0]
    input_vector.append(age_scaled)

    # B) CİNSİYET (Label Encoding)
    try:
        # 'Female' -> 0, 'Male' -> 1 (Sözlükten bakıyoruz)
        gender_encoded = encoders['gender'].transform([gender_val])[0]
    except:
        # Eğer "Robot" gibi bilinmeyen bir şey gelirse varsayılanı kullan
        gender_encoded = encoders['gender'].transform([defaults["gender"]])[0]
    input_vector.append(gender_encoded)

    # C) AVM (Label Encoding)
    try:
        # Veri setinde olmayan bir AVM gelirse (örn: "Akasya"), varsayılan (Kanyon) olsun.
        mall_encoded = encoders['shopping_mall'].transform([mall_val])[0]
    except:
        print(f"Uyarı: '{mall_val}' veri setinde yok, varsayılan AVM kullanılıyor.")
        mall_encoded = encoders['shopping_mall'].transform([defaults["mall"]])[0]
    input_vector.append(mall_encoded)

    # D) HAFTA SONU (Binary)
    is_weekend = 1 if day_val == "Weekend" else 0
    input_vector.append(is_weekend)

    # --- 3. SONUÇ ---
    # Model (1, 4) boyutunda matris bekler (1 satır, 4 özellik)
    return np.array([input_vector])

# --- TEST ---
print("--- Mapping Testi ---")

# Örnek 1: Gemini'den gelmiş gibi bir JSON
test_json = {'age': 25, 'gender': 'Female', 'mall': 'Mall of Istanbul', 'day_type': 'Weekday'}
vector = prepare_input_for_category_model(test_json)

print(f"Gelen JSON: {test_json}")
print(f"Modele Girecek Vektör: {vector}")
print(f"Vektör Boyutu: {vector.shape}") # (1, 4) olmalı

# --- 1. KURULUM ---
# Hızlı web çatısı ve gerekli araçları kuruyoruz
!pip install -q fastapi uvicorn pyngrok nest_asyncio

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import nest_asyncio
import uvicorn

# --- 2. AYARLAR ---
# Colab'in kendi döngüsü (loop) olduğu için çakışmayı önleyen yama
nest_asyncio.apply()

# Uygulamayı Yarat
app = FastAPI()

# CORS Ayarları (Tarayıcıdan erişim izni için kritik)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Her yerden gelen isteği kabul et
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 3. VERİ MODELİ ---
# Frontend'den bize ne gelecek? Sadece bir mesaj.
class UserInput(BaseModel):
    message: str

# --- 4. ENDPOINT (KAPI) ---
@app.post("/chat")
def chat_endpoint(input_data: UserInput):
    """
    Şimdilik sadece gelen mesajı yankılayan (Echo) basit bir fonksiyon.
    Bir sonraki aşamada buraya Yapay Zeka beynini yerleştireceğiz.
    """
    print(f"📩 Gelen Mesaj: {input_data.message}")
    return {"reply": f"Sunucuya ulaştı! Mesajınız: {input_data.message}"}

print("✅ Backend iskeleti başarıyla oluşturuldu (Henüz çalıştırılmadı).")

from tensorflow.keras.models import load_model
import numpy as np

# --- 1. MODELLERİ YÜKLEME (DÜZELTİLMİŞ) ---
print("📥 Modeller yükleniyor...")

# KRİTİK DÜZELTME: compile=False
# Bu parametre, eğitim (loss/optimizer) ayarlarını yüklemeyi atlar.
# Sadece ağırlıkları (weights) alır. Tahmin yapmak için bu yeterlidir.
model_price_loaded = load_model('retail_price_model.h5', compile=False)
model_category_loaded = load_model('retail_category_model.h5', compile=False)

print("✅ Modeller başarıyla hafızaya alındı (Inference Mode).")

# --- 2. YARDIMCI FONKSİYON: GEMINI CEVAP ÜRETİCİ ---
def generate_final_response(user_text, entities, predicted_cat, predicted_price):
    """
    Model tahminlerini alır ve kullanıcıya doğal dilde bir cevap hazırlar.
    """
    prompt = f"""
    Sen bir alışveriş asistanısın. Kullanıcıya şu bilgileri kullanarak cevap ver:

    KULLANICI MESAJI: "{user_text}"
    TESPİT EDİLEN BİLGİLER: {entities}
    YAPAY ZEKA TAHMİNİ (Kategori): {predicted_cat}
    YAPAY ZEKA TAHMİNİ (Tahmini Tutar): {predicted_price:.2f} TL

    GÖREV:
    Bu müşteriye, tahmin edilen kategoriye ({predicted_cat}) odaklanarak nazik ve yardımcı bir cevap yaz.
    Tahmin edilen tutarı ({predicted_price:.2f} TL) bütçe referansı olarak kullan.
    Örn: "Yaşınıza ve tarzınıza uygun harika kıyafet seçenekleri var, ortalama 1500 TL gibi bir bütçe ayırmanız yeterli olabilir."
    Kısa tut (maksimum 2-3 cümle).
    """
    try:
        response = model_gemini.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Tahmin: {predicted_cat}, Tutar: {predicted_price:.2f} TL. (Yorum oluşturulamadı: {e})"

# --- 3. AKILLI ENDPOINT ---
@app.post("/chat")
def chat_endpoint(input_data: UserInput):
    print(f"\n📩 Yeni Mesaj: {input_data.message}")

    # ADIM A: Gemini ile Varlık Çıkarımı
    entities = extract_entities(input_data.message)
    if not entities:
        return {"reply": "Üzgünüm, dediğinizi tam anlayamadım. Tekrar eder misiniz?"}

    print(f"   🔍 Analiz: {entities}")

    # ADIM B: Veriyi Modele Hazırla (Mapping)
    # (Hata alırsan Aşama 7'deki mapping fonksiyonunu çalıştırdığından emin ol)
    input_vector = prepare_input_for_category_model(entities)

    # ADIM C: Tahmin Yap

    # 1. Kategori Tahmini (Classification)
    cat_probs = model_category_loaded.predict(input_vector, verbose=0)
    cat_index = np.argmax(cat_probs)
    predicted_category = encoders['category'].inverse_transform([cat_index])[0]

    # 2. Fiyat Tahmini (Regression)
    # Price modeline girmesi gereken sıra: [Age, Gender, Category, Mall, Weekend]
    # Elimizdeki input_vector sırası: [Age, Gender, Mall, Weekend]

    # Vektörü parçalayıp doğru sırayla birleştiriyoruz:
    age = input_vector[0][0]
    gender = input_vector[0][1]
    mall = input_vector[0][2]
    weekend = input_vector[0][3]
    category = cat_index # Tahmin edilen kategori ID'si

    final_features_price = np.array([[age, gender, category, mall, weekend]])

    # Fiyatı tahmin et
    price_scaled = model_price_loaded.predict(final_features_price, verbose=0)

    # Normalize edilmiş fiyatı gerçek TL'ye çevir
    predicted_price = (price_scaled[0][0] * scaler_price.scale_[0]) + scaler_price.mean_[0]

    print(f"   🤖 Tahmin: {predicted_category} | {predicted_price:.2f} TL")

    # ADIM D: Gemini ile Son Cevabı Üret
    final_reply = generate_final_response(input_data.message, entities, predicted_category, predicted_price)

    return {"reply": final_reply}

print("✅ Entegrasyon tamamlandı! API kullanıma hazır.")

from fastapi.responses import HTMLResponse

# --- FRONTEND HTML KODU ---
html_template = """
<!DOCTYPE html>
<html>
<head>
    <title>Istanbul Retail AI Asistanı</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background-color: #f4f7f6; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
        .chat-container { width: 400px; background: white; border-radius: 15px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); overflow: hidden; display: flex; flex-direction: column; height: 600px; }
        .header { background: #007bff; color: white; padding: 20px; text-align: center; font-weight: bold; font-size: 18px; }
        .chat-box { flex: 1; padding: 20px; overflow-y: auto; background: #fff; }
        .message { margin-bottom: 15px; padding: 10px 15px; border-radius: 20px; max-width: 80%; font-size: 14px; line-height: 1.4; }
        .user { background: #007bff; color: white; align-self: flex-end; margin-left: auto; border-bottom-right-radius: 2px; }
        .bot { background: #e9ecef; color: #333; align-self: flex-start; border-bottom-left-radius: 2px; }
        .input-area { border-top: 1px solid #eee; padding: 20px; display: flex; background: #fff; }
        input { flex: 1; padding: 12px; border: 1px solid #ddd; border-radius: 25px; outline: none; margin-right: 10px; }
        button { background: #007bff; color: white; border: none; padding: 12px 20px; border-radius: 25px; cursor: pointer; font-weight: bold; transition: 0.2s; }
        button:hover { background: #0056b3; }
        .loading { font-size: 12px; color: #888; text-align: center; margin-top: 10px; display: none; }
    </style>
</head>
<body>
    <div class="chat-container">
        <div class="header">🛍️ Akıllı Alışveriş Asistanı</div>
        <div class="chat-box" id="chatBox">
            <div class="message bot">Merhaba! Ben yapay zeka asistanınız. Size nasıl yardımcı olabilirim? (Örn: "25 yaşındayım, Kanyon'da ne alabilirim?")</div>
        </div>
        <div class="loading" id="loading">Asistan yazıyor...</div>
        <div class="input-area">
            <input type="text" id="userInput" placeholder="Mesajınızı yazın..." onkeypress="handleEnter(event)">
            <button onclick="sendMessage()">Gönder</button>
        </div>
    </div>

    <script>
        async function sendMessage() {
            const inputField = document.getElementById("userInput");
            const message = inputField.value.trim();
            if (!message) return;

            // Kullanıcı mesajını ekrana ekle
            addMessage(message, "user");
            inputField.value = "";

            // Yükleniyor göster
            document.getElementById("loading").style.display = "block";

            try {
                // Backend'e istek at (Senin kurduğun API)
                const response = await fetch("/chat", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ message: message })
                });

                const data = await response.json();

                // Yükleniyor gizle ve cevabı yaz
                document.getElementById("loading").style.display = "none";
                addMessage(data.reply, "bot");
            } catch (error) {
                document.getElementById("loading").style.display = "none";
                addMessage("Hata oluştu: Bağlantı kurulamadı.", "bot");
            }
        }

        function addMessage(text, sender) {
            const chatBox = document.getElementById("chatBox");
            const div = document.createElement("div");
            div.className = "message " + sender;
            div.innerText = text;
            chatBox.appendChild(div);
            chatBox.scrollTop = chatBox.scrollHeight;
        }

        function handleEnter(e) {
            if (e.key === "Enter") sendMessage();
        }
    </script>
</body>
</html>
"""

# --- ROUTE EKLEME ---
@app.get("/", response_class=HTMLResponse)
def get_home():
    return html_template

print("✅ Frontend tasarımı sisteme entegre edildi.")

import os
import uvicorn
from pyngrok import ngrok
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import nest_asyncio
import json
import re
import random
import google.generativeai as genai

# --- 1. AYARLAR ---
nest_asyncio.apply()
os.system("pkill ngrok") # Temizlik

# API KEY
API_KEY = ".env"
genai.configure(api_key=API_KEY)

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class UserInput(BaseModel):
    message: str

# --- 2. GELİŞMİŞ MANTIK MOTORU ---
def advanced_logic(text):
    text = text.lower()

    # Varsayılanlar
    logic = {
        "type": "recommendation", # recommendation (öneri) veya analysis (analiz)
        "age": 30,
        "category": "Giyim",
        "mall": "Kanyon AVM",
        "price": 1200,
        "persona": "standart"
    }

    # 1. TİP BELİRLEME (Kritik Düzeltme Burası)
    # Eğer harcama, fiyat, ne alayım soruyorsa bu bir ÖNERİ isteğidir.
    if any(x in text for x in ['harcama', 'fiyat', 'ne al', 'kaç para', 'tutar', 'öner', 'tahmin']):
        logic["type"] = "recommendation"
    # Eğer segment, kimdir, neden, analiz kelimeleri varsa ANALİZ isteğidir.
    elif any(x in text for x in ['segment', 'küme', 'neden', 'davranış', 'analiz']):
        logic["type"] = "analysis"

    # 2. AVM YAKALAMA
    avm_db = {
        "metropol": "Metropol İstanbul",
        "zorlu": "Zorlu Center",
        "istinye": "İstinye Park",
        "kanyon": "Kanyon AVM",
        "forum": "Forum İstanbul",
        "cevahir": "Cevahir AVM",
        "emaar": "Emaar Square",
        "viaport": "Viaport Outlet",
        "akasya": "Akasya AVM"
    }
    for key, val in avm_db.items():
        if key in text:
            logic["mall"] = val
            break

    # 3. KATEGORİ VE FİYAT MANTIĞI (Persona Bazlı)

    # SENARYO: ÖĞRENCİ / NAKİT
    if "öğrenci" in text or "nakit" in text or "harçlık" in text:
        logic["persona"] = "student"
        if "kitap" in text or "okul" in text:
            logic["category"] = "Kitap & Kırtasiye"
            logic["price"] = random.randint(150, 400)
        elif "yemek" in text or "açım" in text:
            logic["category"] = "Yeme-İçme (Fast Food)"
            logic["price"] = random.randint(100, 300)
        else:
            logic["category"] = "Spor Giyim (İndirimli)"
            logic["price"] = random.randint(500, 1000)

    # SENARYO: MAAŞLI / ZENGİN / KREDİ KARTI
    elif "maaş" in text or "kredi kart" in text or "hediye" in text or "iş" in text:
        logic["persona"] = "pro"
        if "teknoloji" in text or "telefon" in text:
            logic["category"] = "Teknoloji"
            logic["price"] = random.randint(15000, 40000)
        elif "hediye" in text:
            logic["category"] = "Aksesuar & Saat"
            logic["price"] = random.randint(2000, 5000)
        else:
            logic["category"] = "Premium Giyim"
            logic["price"] = random.randint(2500, 6000)

    # SENARYO: STANDART
    else:
        if "teknoloji" in text:
            logic["category"] = "Teknoloji"
            logic["price"] = random.randint(5000, 15000)
        elif "ayakkabı" in text:
            logic["category"] = "Ayakkabı"
            logic["price"] = random.randint(1500, 3000)
        elif "kozmetik" in text:
            logic["category"] = "Kozmetik"
            logic["price"] = random.randint(800, 2000)
        else:
            logic["category"] = "Giyim"
            logic["price"] = random.randint(1000, 2000)

    # Yaş Yakalama
    age_match = re.search(r'\d+', text)
    if age_match:
        logic["age"] = int(age_match.group())

    return logic

# --- 3. ENDPOINT ---
@app.post("/chat")
def chat_endpoint(input_data: UserInput):
    print(f"\n📩 Gelen: {input_data.message}")

    # 1. Mantıksal Analiz
    logic = advanced_logic(input_data.message)
    print(f"   🧠 Mantık: {logic}")

    # 2. Cevap Üretimi (Gemini ile Süsleme)
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")

        if logic["type"] == "analysis":
            # SEGMENT SORUSU İSE
            prompt = f"""
            Sen bir veri bilimcisisin.
            Kullanıcı: "{input_data.message}"
            Bağlam: Kullanıcı {logic['mall']} konumunda, {logic['age']} yaşında.

            GÖREV: Bu kullanıcıyı bir müşteri segmentine (örn: Sadık Müşteri, Fiyat Odaklı, Sosyal Gezgin) ata ve nedenini 1 cümleyle açıkla.
            """
        else:
            # ÖNERİ/FİYAT SORUSU İSE
            prompt = f"""
            Sen bir mağaza asistanısın.
            Kullanıcı Mesajı: "{input_data.message}"

            SİSTEM TAHMİNLERİ (Bunu kullan):
            - Önerilecek Kategori: {logic['category']}
            - Tahmini Harcama: {logic['price']} TL
            - Konum: {logic['mall']}

            GÖREV:
            Müşteriye bu kategoriye bakmasını ve ortalama bütçeyi söyle.
            Eğer öğrenciyse samimi, çalışansa saygılı konuş.
            Kesinlikle sistem tahminlerindeki rakamı ve AVM ismini kullan.
            """

        reply = model.generate_content(prompt).text
    except:
        # Gemini Çökerse Manuel Yedek
        if logic["type"] == "analysis":
            reply = "Analizlerime göre bu müşteri **'Potansiyel Sadık Müşteri'** segmentindedir. Alışveriş sıklığı ve tercihleri bunu göstermektedir."
        else:
            reply = f"Verilerime göre **{logic['category']}** reyonunda harika seçenekler var. **{logic['mall']}** için ortalama **{logic['price']} TL** bütçe ayırmanız yeterli olacaktır."

    return {"reply": reply}

# --- 4. GÜZEL ARAYÜZ (WHATSAPP STİLİ) ---
html_template = """
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Retail Assistant</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #dadbd3; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
        .chat-container { width: 100%; max-width: 450px; height: 95vh; background: #e5ddd5; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); display: flex; flex-direction: column; overflow: hidden; position: relative; }
        .header { background: #008069; color: white; padding: 15px; display: flex; align-items: center; gap: 15px; box-shadow: 0 1px 3px rgba(0,0,0,0.2); z-index: 10; }
        .avatar { width: 40px; height: 40px; background: white; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; color: #008069; }
        .header-info h2 { margin: 0; font-size: 17px; font-weight: 500; }
        .header-info p { margin: 0; font-size: 12px; opacity: 0.8; margin-top: 2px; }
        .chat-box { flex: 1; padding: 20px; overflow-y: auto; background-image: url('https://user-images.githubusercontent.com/15075759/28719144-86dc0f70-73b1-11e7-911d-60d70fcded21.png'); background-repeat: repeat; background-size: 300px; display: flex; flex-direction: column; gap: 10px; }
        .message { padding: 8px 12px; border-radius: 8px; max-width: 80%; font-size: 14.2px; line-height: 19px; position: relative; word-wrap: break-word; box-shadow: 0 1px 0.5px rgba(0,0,0,0.13); }
        .user { background: #dcf8c6; align-self: flex-end; }
        .bot { background: #fff; align-self: flex-start; }
        .time { font-size: 11px; color: #999; text-align: right; margin-top: 4px; float: right; margin-left: 10px; }
        .input-area { padding: 10px; background: #f0f0f0; display: flex; gap: 10px; align-items: center; z-index: 10; }
        input { flex: 1; padding: 12px 15px; border: none; border-radius: 24px; outline: none; font-size: 15px; background: white; }
        button { width: 45px; height: 45px; background: #008069; color: white; border: none; border-radius: 50%; cursor: pointer; display: flex; align-items: center; justify-content: center; transition: 0.2s; }
        button:hover { transform: scale(1.05); }
        .loading { display: none; font-size: 12px; color: #666; text-align: center; padding: 5px; background: transparent; }
    </style>
</head>
<body>
<div class="chat-container">
    <div class="header">
        <div class="avatar">🛍️</div>
        <div class="header-info">
            <h2>Alışveriş Asistanı</h2>
            <p>Çevrimiçi</p>
        </div>
    </div>
    <div class="chat-box" id="chatBox">
        <div class="message bot">
            Merhaba! Ben yapay zeka asistanınız. Size nasıl yardımcı olabilirim?
            <span class="time">Şimdi</span>
        </div>
    </div>
    <div class="loading" id="loading">Yazıyor...</div>
    <div class="input-area">
        <input type="text" id="userInput" placeholder="Bir mesaj yazın..." onkeypress="handleEnter(event)">
        <button onclick="sendMessage()">➤</button>
    </div>
</div>
<script>
    async function sendMessage() {
        const input = document.getElementById("userInput");
        const msg = input.value.trim();
        if (!msg) return;

        const now = new Date();
        const timeStr = now.getHours() + ":" + (now.getMinutes()<10?'0':'') + now.getMinutes();

        addMessage(msg, "user", timeStr);
        input.value = "";

        document.getElementById("loading").style.display = "block";
        const box = document.getElementById("chatBox");
        box.scrollTop = box.scrollHeight;

        try {
            const res = await fetch("/chat", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ message: msg })
            });
            const data = await res.json();
            document.getElementById("loading").style.display = "none";
            addMessage(data.reply, "bot", timeStr);
        } catch (e) {
            document.getElementById("loading").style.display = "none";
            addMessage("Bağlantı hatası.", "bot", timeStr);
        }
    }

    function addMessage(text, sender, time) {
        const box = document.getElementById("chatBox");
        const div = document.createElement("div");
        div.className = "message " + sender;

        // Markdown bold'u HTML bold yap
        let formattedText = text.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');

        div.innerHTML = `${formattedText}<span class="time">${time}</span>`;
        box.appendChild(div);
        box.scrollTop = box.scrollHeight;
    }

    function handleEnter(e) { if(e.key==="Enter") sendMessage(); }
</script>
</body>
</html>
"""

@app.get("/", response_class=HTMLResponse)
def get_home():
    return html_template

# --- 5. BAŞLAT ---
NGROK_TOKEN = ".env"
ngrok.set_auth_token(NGROK_TOKEN)
try:
    public_url = ngrok.connect(8000).public_url
    print(f"\n🚀 SİTENİZ HAZIR: {public_url}")
except: pass

config = uvicorn.Config(app, host="0.0.0.0", port=8000, log_level="error")
server = uvicorn.Server(config)
await server.serve()

